---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Gather facts for EC2 instances
    ec2_instance_facts:
      region: "{{ aws_region }}"
      filters:
        "tag:Environment": "{{ environment_name | default('Development') }}"
        instance-state-name: "{{ item }}"
    with_items:
      - running
      - stopped
    register: ec2_instances

#  - name: Display output
#    debug:
#      var: ec2_instances

#  - name: print it
#    debug:
#      msg="instance_id is - {{ item.instance_id }}"
#    with_items: "{{ec2_instances.results[0].instances}}"


  - name: terminate ec2 instances
    ec2:
      region: "{{ aws_region }}"
      state: absent
      instance_id: "{{ item.instance_id }}"
    with_items: "{{ ec2_instances.results[0].instances }}"
